# refer to https://prettier.io/docs/en/options.html
---
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: 'as-needed'
trailingComma: 'es5'
bracketSpacing: true
arrowParens: 'always'
proseWrap: 'preserve'
endOfLine: 'lf'
# HTML/CSS
htmlWhitespaceSensitivity: 'css'
# React specific
jsxSingleQuote: false
bracketSameLine: false
